name: GitHub Pages
on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          user_name: AkulMehra
          user_email: akulfifa@gmail.com

      - name: Add custom headers for cross-origin isolation
        run: |
          echo "Cross-Origin-Opener-Policy: same-origin" >> .git/attributes
          echo "Cross-Origin-Embedder-Policy: require-corp" >> .git/attributes
